# Generated by Django 6.0.3 on 2026-03-19 15:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=1024)),
                ('is_deleted', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.boardcolumn')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectboard')),
            ],
        ),
        migrations.CreateModel(
            name='TaskMembers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=24)),
                ('role', models.CharField(choices=[('ASG', 'Assignee'), ('REV', 'Reviewer')], default='ASG', max_length=3)),
                ('is_deleted', models.BooleanField(default=False)),
                ('taskitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.taskitem')),
            ],
        ),
    ]
