# Generated by Django 6.0.3 on 2026-03-22 18:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_taskitem_created_at_taskitem_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskitem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='taskmembers',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
