# Generated by Django 6.0.3 on 2026-03-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectboard',
            name='message_id',
        ),
        migrations.AddField(
            model_name='boardcolumn',
            name='message_id',
            field=models.CharField(default='', max_length=24),
        ),
    ]
