# Generated by Django 6.0.3 on 2026-03-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_projectboard_message_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectboard',
            name='message_id',
            field=models.CharField(default='', max_length=24),
        ),
    ]
