# Generated by Django 6.0.3 on 2026-03-20 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectboard_message_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardcolumn',
            name='message_id',
        ),
    ]
