# Generated by Django 6.0.3 on 2026-03-25 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_boardcolumn_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectboard',
            old_name='server_id',
            new_name='guild_id',
        ),
    ]
