# Generated by Django 6.0.3 on 2026-03-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_rename_server_id_projectboard_guild_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectboard',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
