# Generated by Django 6.0.3 on 2026-03-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_projectboard_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectboard',
            name='created_by',
            field=models.CharField(default='', max_length=24),
        ),
    ]
