# Generated by Django 6.0.3 on 2026-03-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_projectboard_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardcolumn',
            name='created_by',
            field=models.CharField(default='', max_length=24),
        ),
        migrations.AddField(
            model_name='boardcolumn',
            name='updated_by',
            field=models.CharField(default='', max_length=24),
        ),
    ]
