# Generated by Django 6.0.3 on 2026-03-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_boardcolumn_created_by_boardcolumn_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardcolumn',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
